Repository NVIDIA/physicsnemo-sym, pull requests merged in 2023-07, with the labels that each got.

#40 fix: arch from config bug
  CHANGELOG.md
  modulus/sym/models/arch.py
Labels: bug, 3 - Ready for Review

#42 Fixing FusedSiLU tests
  CHANGELOG.md
  test/test_models/test_activation.py
Labels: bug

#44 Reduce batch size for gradient enhanced annular ring
  examples/annular_ring/annular_ring_gradient_enhanced/conf/config.yaml
Labels: 5 - Ready to Merge, ! - Release
